# Generated by Django 5.1.4 on 2025-02-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField(default=0)),
                ('totais', models.IntegerField(default=0)),
            ],
        ),
    ]
