# Generated by Django 5.1.4 on 2025-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoMental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='op1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='op2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='partida',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
