# Generated by Django 5.1.4 on 2025-03-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoMental', '0002_partida_op1_partida_op2_partida_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='op2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
