# Generated by Django 5.1.4 on 2025-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoMental', '0003_alter_partida_op2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='op1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
