# Generated by Django 5.2 on 2025-08-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoMental', '0004_alter_partida_op1'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
